FROM openjdk:8-jdk-alpine
ARG JAR_FILE=spring-petclinic-1.5.1.jar
ENV CONTRAST__API__URL ${CONTRAST_API_URL}
ENV CONTRAST__API__API_KEY ${CONTRAST_API_API_KEY}
ENV CONTRAST__API__SERVICE_KEY ${CONTRAST_API_SERVICE_KEY}
ENV CONTRAST__API__USER_NAME ${CONTRAST_API_USER_NAME}
ENV CONTRAST__APPLICATION__NAME "PetClinicOnDocker"
COPY contrast.jar contrast.jar
ENV JAVA_TOOL_OPTIONS "-javaagent:contrast.jar"
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar", "--server.port=8001"]
