name: Java Agent Check New

on:
  workflow_dispatch:

jobs:
  agentcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up JDK 11
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        id: get-newer-version
        run: |
          ./agent_check.sh
          echo "CURRENT_VERSION=`cat ./current_version.txt`" >> "$GITHUB_OUTPUT"
          echo "NEWER_VERSION=`cat ./newer_version.txt`" >> "$GITHUB_OUTPUT"
      - name: Download Java Agent
        id: agent_download
        run: |
            mvn clean
            mvn -q dependency:copy-dependencies
            mv target/dependency/contrast-*.jar ./contrast.jar
      - name: Build PetClinic
        run: |
            docker build -t petclinic .
      - name: Launch PetClinic
        id: launch_petclinic
        env:
          CONTRAST_API_URL: ${{ env.CONTRAST_URL }} 
          CONTRAST_API_API_KEY: ${{ secrets.CONTRAST_API_KEY }} 
          CONTRAST_API_SERVICE_KEY: ${{ secrets.CONTRAST_SERVICE_KEY }} 
          CONTRAST_API_USER_NAME: ${{ secrets.CONTRAST_USER_NAME }} 
        run: |
            docker run -d --network host --name petclinic-app petclinic
            docker ps
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Set up Playwright
        run: |
          playwright install
      - name: Build radar
        run: |
          python Davis.py

