name: Java Agent Check New

on:
  workflow_dispatch:

jobs:
  agentcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up JDK 17
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        id: get-newer-version
        run: |
          ./agent_check.sh
          echo "CURRENT_VERSION=`cat ./current_version.txt`" >> "$GITHUB_OUTPUT"
          echo "NEWER_VERSION=`cat ./newer_version.txt`" >> "$GITHUB_OUTPUT"
      - name: Download Java Agent
        id: agent_download
        run: |
            mvn clean
            mvn -q dependency:copy-dependencies
            mv target/dependency/contrast-*.jar ./contrast.jar
      - name: Clone PetClinicDemo
        uses: actions/checkout@v4.2.1
        with:
          repository: 'turbou/PetClinicDemo'
          path: 'petclinicdemo'
      - name: Set up JDK 8
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Download Java Agent
        id: agent_download
        run: |
            cd petclinicdemo
            mvn clean package -DskipTests
      - name: Build PetClinic Docker Image
        run: |
            docker build -t petclinic .
      - name: Launch PetClinic
        id: launch_petclinic
        run: |
            docker run -d \
              -e CONTRAST__API__TOKEN="${{ secrets.CONTRAST_API_TOKEN }}" \
              -e CONTRAST__SERVER__ENVIRONMENT="development" \
              -e CONTRAST__SERVER__NAME="GithubPipeline" \
              -e CONTRAST__APPLICATION__NAME="PetClinicForAgentTest" \
              -e CONTRAST__AGENT__LOGGER__LEVEL="DEBUG" \
              -e CONTRAST__AGENT__LOGGER__PATH="/tmp/agent.log" \
              -e CONTRAST__AGENT__POLLING__APP_ACTIVITY_MS=3000 \
              -e CONTRAST__AGENT__POLLING__SERVER_ACTIVITY_MS=3000 \
              -e CONTRAST__API__TIMEOUT_MS=3000 \
              -e CONTRAST__APPLICATION__SESSION_METADATA="pipeline_id=${{ github.run_id }}" \
              -v /tmp:/tmp \
              --network host \
              --name petclinic-app petclinic
            sleep 90
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Set up Playwright
        run: |
          playwright install
      - name: Reset Contrast Application
        env:
          CONTRAST_AUTHORIZATION: ${{ secrets.CONTRAST_AUTHORIZATION }} 
          CONTRAST_API_KEY: ${{ secrets.CONTRAST_API_KEY }} 
          CONTRAST_ORG_ID: ${{ vars.CONTRAST_ORG_ID }} 
        run: |
          python reset_app.py
          sleep 60
      - name: Run Playwrite
        run: |
          python Davis.py
          sleep 30
      - name: Print container log
        run: docker logs petclinic-app
      - name: Print agent log
        run: cat /tmp/agent.log
      - name: Verify result
        env:
          CONTRAST_AUTHORIZATION: ${{ secrets.CONTRAST_AUTHORIZATION }} 
          CONTRAST_API_KEY: ${{ secrets.CONTRAST_API_KEY }} 
          CONTRAST_ORG_ID: ${{ vars.CONTRAST_ORG_ID }} 
        run: |
          python verify.py

